language: node_js
node_js:
  - "0.12"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp build
deploy:
  provider: heroku
  api_key:
    secure: ZTFuct58wXXxThTNoM4yfB222QVjUwcWr6J+tWHdaDZ3RCHJKuvNdza/M1wnRfEeTuw43plZHXkUnm4mkYCwCa/FeVOyqI41jB9jNaV74p+A0pGLAS9Q+stjZ6eVLArBWa0xqV1iiefjXe6no6fyGBBPv0Wpi4XBF/Cr8qFlNBeq6U8ue4pXde3T3loWs+nk9V4o1TeresfvULH/oCqk3dcmhNgzc2Dpm
  app: calm-hamlet-4885
  on:
    repo: d3trax/agileConf
  skip_cleanup: true
