language: node_js
node_js:
  - "0.12"
before_script:
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - jspm registry create bower jspm-bower-endpoint -y
  - jspm install -y
  - jspm install aurelia-framework
  - jspm install aurelia-http-client
  - jspm install aurelia-router
  - tsd install
  - npm install -g karma-cli
script: gulp
deploy:
  provider: heroku
  api_key: "373aee47-beae-48f4-bc83-89df1719ce2f"